# Generated by Django 3.2 on 2021-05-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_django', '0005_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passw',
            field=models.CharField(max_length=100),
        ),
    ]
