# Generated by Django 3.2.3 on 2021-05-28 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_django', '0006_alter_user_passw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='passw',
            field=models.CharField(max_length=999),
        ),
    ]
